Repository mindticas/mindticas2025-back, pull requests merged in 2025-03, with the labels that each got.

#17 chore: rename field in dto
  src/dtos/appointment.register.dto.ts
  src/services/appointment.service.ts
Labels: fix

#20 chore: change url cors
  src/main.ts
Labels: enhancement

#21 Feature/seeds
  package.json
  src/app.module.ts
  src/modules/index.ts
  src/modules/role.module.ts
  src/modules/seed.module.ts
  src/modules/user.module.ts
  src/scripts/run-seeds.ts
  src/seeds/index.ts
  src/seeds/role.seed.ts
  src/seeds/user.seed.ts
  src/services/index.ts
  src/services/seed.service.ts
Labels: feature

#22 fix: remove trailing slash `/` from CORS origin URL
  src/main.ts
Labels: fix

#24 Feature/setting up whatsapp
  package.json
  src/app.module.ts
  src/controllers/index.ts
  src/controllers/whatsapp.controller.ts
  src/modules/appointment.module.ts
  src/modules/index.ts
  src/modules/whatsapp.module.ts
  src/services/appointment.service.ts
  src/services/index.ts
  src/services/whatsapp.service.ts
  src/templates/whatsapp.messages.json
  tsconfig.json
  yarn.lock
Labels: refactor

#23 feature: Setting up WhatsApp
  package.json
  src/app.module.ts
  src/controllers/index.ts
  src/controllers/whatsapp.controller.ts
  src/modules/appointment.module.ts
  src/modules/index.ts
  src/modules/whatsapp.module.ts
  src/services/appointment.service.ts
  src/services/index.ts
  src/services/whatsapp.service.spec.ts
  src/services/whatsapp.service.ts
  src/templates/whatsapp.messages.json
  tsconfig.json
  yarn.lock
Labels: feature

#28 feature: appointment cancellation
  src/services/whatsapp.service.ts
Labels: feature

#27 feature: Clients | Remainder of an appointment
  package.json
  src/app.module.ts
  src/controllers/whatsapp.controller.ts
  src/services/appointment.service.ts
  src/services/whatsapp.service.ts
Labels: feature

#26 Feature/scrum 57 back appointment confirmation
  package.json
  src/app.module.ts
  src/controllers/whatsapp.controller.ts
  src/modules/appointment.module.ts
  src/services/appointment.service.ts
  src/services/whatsapp.service.ts
  src/templates/whatsapp.messages.json
  src/utils/messageFormatter.ts
Labels: feature

#29 feature: CRUD Appointment
  src/controllers/appointment.controller.spec.ts
  src/controllers/appointment.controller.ts
  src/dtos/appointment.update.dto.ts
  src/dtos/create.treatment.dto.ts
  src/dtos/index.ts
  src/dtos/update.treatment.dto.ts
  src/services/appointment.service.spec.ts
  src/services/appointment.service.ts
Labels: feature

#35 Feature/scrum 16 back admin login
  .eslintrc.js
  package.json
  src/app.module.ts
  src/auth/auth.guard.ts
  src/controllers/auth.controller.spec.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/dtos/user.login.dto.ts
  src/modules/auth.module.ts
  src/modules/user.module.ts
  src/services/auth.service.spec.ts
  src/services/auth.service.ts
  src/services/user.service.spec.ts
  src/services/user.service.ts
Labels: feature

#34 feature: Sync Google Calendar
  package.json
  src/app.module.ts
  src/config/google.config.ts
  src/modules/appointment.module.ts
  src/modules/google.calendar.module.ts
  src/modules/index.ts
  src/scripts/google.calendar.get-refresh-token.ts
  src/services/appointment.service.spec.ts
  src/services/appointment.service.ts
  src/services/google.calendar.service.spec.ts
  src/services/google.calendar.service.ts
  src/services/index.ts
  src/services/whatsapp.service.ts
  tsconfig.json
Labels: feature

#37 Feature/scrum 16 back admin login
  .eslintrc.js
  package.json
  src/app.module.ts
  src/auth/auth.guard.ts
  src/controllers/auth.controller.spec.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/dtos/user.login.dto.ts
  src/modules/auth.module.ts
  src/modules/user.module.ts
  src/services/auth.service.spec.ts
  src/services/auth.service.ts
  src/services/user.service.spec.ts
  src/services/user.service.ts
Labels: duplicate, feature

#39 Fix treatment controller
  src/controllers/treatment.controller.ts
Labels: bug

#38 Feature/scrum 50 back crud appointment
  src/controllers/appointment.controller.ts
  src/dtos/appointment.update.dto.ts
  src/services/appointment.service.ts
Labels: fix

#40 Feature/scrum 50 back crud appointment
  src/services/appointment.service.ts
  src/utils/appointment.validations.ts
  yarn.lock
Labels: refactor

#41 fix: update method
  src/services/appointment.service.ts
Labels: fix
