Repository mindticas/mindticas2025-back, pull requests merged in 2025-04, with the labels that each got.

#42 fix: Returns 401 code if the username is incorrect, before extracting…
  src/services/auth.service.ts
Labels: bug

#44 feature: Security Tweaks
  src/controllers/appointment.controller.ts
  src/controllers/treatment.controller.ts
Labels: feature

#43 refactor: Refactoring Code
  package.json
  src/controllers/google.calendar.controller.ts
  src/controllers/index.ts
  src/data-source.ts
  src/entities/appointment.entity.ts
  src/entities/google-token.entity.ts
  src/entities/index.ts
  src/main.ts
  src/migration/1743529941664-Add-Appointment.eventId-and-Create-GoogleToken-entity.ts
  src/modules/appointment.module.ts
  src/modules/google.calendar.module.ts
  src/modules/index.ts
  src/modules/schedule.tasks.module.ts
  src/services/appointment.service.ts
  src/services/google-token.service.ts
  src/services/google.calendar.service.ts
  src/services/index.ts
  src/services/schedule.tasks.service.ts
  src/services/whatsapp.service.ts
Labels: refactor

#47 fix: appointment time
  package.json
  src/services/appointment.service.ts
Labels: fix

#46 feature: Support for Statistics
  src/app.module.ts
  src/controllers/index.ts
  src/controllers/statistics.controller.ts
  src/dtos/index.ts
  src/dtos/response.statistics.dto.ts
  src/modules/index.ts
  src/modules/statistics.module.ts
  src/services/index.ts
  src/services/statistics.service.spec.ts
  src/services/statistics.service.ts
Labels: feature

#45 feature: Schedule Tweaks
  src/app.module.ts
  src/controllers/schedule.controller.spec.ts
  src/controllers/schedule.controller.ts
  src/data-source.ts
  src/dtos/index.ts
  src/dtos/schedule.create.dto.ts
  src/dtos/schedule.update.dto.ts
  src/entities/index.ts
  src/entities/schedule.entity.ts
  src/migration/1743706156376-add_schedule_entity.ts
  src/migration/1744052044356-add_unique_index_in_day_field.ts
  src/modules/index.ts
  src/modules/schedule.module.ts
  src/modules/seed.module.ts
  src/seeds/index.ts
  src/seeds/schedule.seed.ts
  src/services/schedue.service.ts
  src/services/schedule.service.spec.ts
  src/services/seed.service.ts
Labels: feature

#48 chore: add user name in get method
  src/controllers/appointment.controller.ts
  src/dtos/appointment.dto.ts
  src/dtos/appointment.get.response.dto.ts
  src/dtos/index.ts
  src/dtos/user.name.get.dto.ts
  src/services/appointment.service.ts
Labels: enhancement

#51 feature: filters support
  src/controllers/customer.controller.ts
  src/services/customer.service.ts
Labels: feature

#50 Refactor/refactoring for release
  src/app.module.ts
  src/config/auth.config.ts
  src/config/google.config.ts
  src/config/whapi.config.ts
  src/controllers/google.calendar.controller.ts
  src/controllers/schedule.controller.spec.ts
  src/controllers/schedule.controller.ts
  src/entities/appointment.entity.ts
  src/main.ts
  src/migration/1744154904187-ChangeScheduledStartToTimestamptz.ts.ts
  src/modules/appointment.module.ts
  src/modules/auth.module.ts
  src/modules/customer.module.ts
  src/modules/google.calendar.module.ts
  src/modules/role.module.ts
  src/modules/schedule.module.ts
  src/modules/schedule.tasks.module.ts
  src/modules/statistics.module.ts
  src/modules/treatment.module.ts
  src/modules/user.module.ts
  src/modules/whatsapp.module.ts
  src/services/appointment.service.ts
  src/services/google.calendar.service.ts
  src/services/schedule.service.spec.ts
  src/services/schedule.service.ts
  src/services/schedule.tasks.service.ts
  src/services/whatsapp.service.ts
  src/templates/whatsapp.messages.json
  src/utils/messageFormatter.ts
Labels: refactor

#55 chore: Solving comments
  src/services/customer.service.ts
  src/utils/customer.filter.ts
Labels: enhancement

#54 fix: fixing the logic for release
  src/app.module.ts
  src/config/google.config.ts
  src/controllers/google.calendar.controller.ts
  src/modules/google.calendar.module.ts
  src/modules/schedule.tasks.module.ts
  src/services/appointment.service.ts
  src/services/google.calendar.service.ts
  src/services/schedule.tasks.service.ts
  src/services/whatsapp.service.ts
  src/templates/whatsapp.messages.json
  src/utils/messageFormatter.ts
Labels: bug, refactor

#56 chore: seeds
  src/modules/seed.module.ts
  src/seeds/index.ts
  src/seeds/role.seed.ts
  src/seeds/schedule.seed.ts
  src/seeds/treatments.seed.ts
  src/seeds/user.seed.ts
  src/services/seed.service.ts
Labels: enhancement

#57 refactor: Use luxon to format dates due to node.js of vercel is not b…
  src/utils/messageFormatter.ts
Labels: bug, refactor

#60 config: vercel seed
  package.json
  src/seeds/treatments.seed.ts
Labels: enhancement

#62 Config/vercel seed
  package.json
  src/main.ts
Labels: fix

#63 Development
  src/main.ts
  src/seeds/treatments.seed.ts
Labels: release

#64 feature: User CRUD
  src/controllers/user.controller.ts
  src/dtos/index.ts
  src/dtos/user.create.dto.ts
  src/dtos/user.get.response.dto.ts
  src/dtos/user.update.dto.ts
  src/services/customer.service.ts
  src/services/user.service.spec.ts
  src/services/user.service.ts
  src/utils/customer.filter.ts
  src/utils/filter.ts
Labels: feature

#66 chore: get user by id
  src/controllers/user.controller.ts
  src/services/user.service.ts
Labels: enhancement

#67 chore: add treatment relation in user get
  src/services/user.service.ts
Labels: enhancement

#68 bugifx: scheduling
  src/utils/appointment.validations.ts
Labels: fix

#69 chore: user panel
  src/controllers/role.controller.ts
  src/dtos/index.ts
  src/dtos/role.get.response.dto.ts
  src/modules/role.module.ts
  src/services/index.ts
  src/services/role.service.ts
  src/services/user.service.ts
Labels: enhancement

#70 chore: Solving comments
  src/dtos/role.get.response.dto.ts
Labels: enhancement

#72 feat: Support for Excel file export
  package.json
  src/controllers/statistics.controller.ts
  src/modules/statistics.module.ts
  src/modules/treatment.module.ts
  src/services/statistics.service.spec.ts
  src/services/statistics.service.ts
  src/services/treatment.service.ts
Labels: feature

#74 feature: CRUD treatments
  src/controllers/treatment.controller.ts
  src/services/treatment.service.ts
  src/utils/filter.ts
Labels: feature
