Repository mindticas/mindticas2025-back, pull requests merged in 2025-02, with the labels that each got.

#10 Bugfix/correct relationships
  src/entities/appointment.entity.ts
  src/entities/customer.entity.ts
  src/entities/index.ts
  src/entities/role.entity.ts
  src/entities/service.entity.ts
  src/entities/user.entity.ts
  src/entity/index.ts
  src/migration/1739835176109-pluralize-ManyToMany-colums-and-fix-relationships.ts
Labels: bug

#11 feature: adds services Menu functionality
  package.json
  src/app.module.ts
  src/controllers/index.ts
  src/controllers/treatment.controller.ts
  src/data-source.ts
  src/dtos/create-treatment.dto.ts
  src/dtos/index.ts
  src/dtos/update-treatment.dto.ts
  src/entities/appointment.entity.ts
  src/entities/index.ts
  src/entities/treatment.entity.ts
  src/main.ts
  src/modules/index.ts
  src/modules/treatment.module.ts
  src/services/index.ts
  src/services/treatment.service.ts
  yarn.lock
Labels: feature

#12 fix: remove files mentioned in the index files
  src/app.module.ts
  src/controllers/index.ts
  src/data-source.ts
  src/modules/index.ts
  src/services/index.ts
Labels: fix

#13 feature: add scheduling and appointment
  src/app.module.ts
  src/controllers/appointment.controller.ts
  src/controllers/customer.controller.ts
  src/controllers/index.ts
  src/dtos/appointment.register.dto.ts
  src/dtos/customer.register.dto.ts
  src/dtos/index.ts
  src/entities/appointment.entity.ts
  src/enums/appointments.status.enum.ts
  src/migration/1740170271079-change_scheduledat_to_scheduledstart_in_appointment_entity.ts
  src/migration/1740606549906-fix-appointment-changes.ts
  src/modules/appointment.module.ts
  src/modules/customer.module.ts
  src/modules/index.ts
  src/services/appointment.service.ts
  src/services/customer.service.ts
  src/services/index.ts
Labels: feature

#14 chore(test): Add service menu functionality test
  jest.config.ts
  src/app.controller.spec.ts
  src/controllers/treatment.controller.spec.ts
  src/controllers/treatment.controller.ts
  src/entities/treatment.entity.spec.ts
  src/entities/treatment.entity.ts
  src/main.ts
  src/migration/1740512621075-Makes-name-property-of-treatment-entity-unique.ts
  src/modules/treatment.module.ts
  src/services/treatment.service.spec.ts
  src/services/treatment.service.ts
Labels: test
